### ISSUE TITLE
Doesnt seen to read my blockstack id.  I get nothing in read/write approve box, says no ids

### ISSUE THREAD

**Issue by MedBTG** [ntheile/blockusign#78]
I run stealthy and graphite and few other bstack apps.  Any help?  Thanks Joe

**Comment by ntheile** [comment]
do you normally login to stealthy and graphite using the locally installed blockstack browser on your computer here http://localhost:8888 ? 

I force login thru the blockstack web browser at https://browser.blockstack.org due to issues on mobile and safari. 

Are you able to login at  https://browser.blockstack.org? You can export your 12 word secret recovery key from here: http://localhost:8888/account/backup and import it into the blockstack web.

**Comment by MedBTG** [comment]
do you normally login to stealthy and graphite using the locally installed blockstack browser on your computer here http://localhost:8888 ?    YES

Are you able to login at https://browser.blockstack.org? You can export your 12 word secret recovery key from here: http://localhost:8888/account/backup and import it into the blockstack web.
THEY ARE ALREADY BOTH THE SAME.  ARENT THEY THE SAME ID?

**Comment by MedBTG** [comment]
FYI When I try to invoke Blockusign from a vault pdf,  I get spinning half circle in a infinite loop

**Comment by MedBTG** [comment]
FYI Updated ublockstack chrome extension and I go id to populate.  thx  great stuff
